name: hydrocon_env
channels:
  - conda-forge
dependencies:
  - python=3.7
  - python-dotenv
  - jupyterlab
  - ipympl
  - ipywidgets
  - jupyter
  - gdal
  - geopandas
  - matplotlib
  - numpy
  - pandas
  - pathlib
  - pyproj
  - pytz
  - rasterio
  - scikit-learn
  - scipy
  - seaborn
  - shapely
  - typing
  - pip
  - pip:
    - -r requirements.txt
    - bomwater
    - pysheds
    - scikits.bootstrap
 